### ISSUE TITLE
Question about terminating libraries when using XMP in a Windows property handler

### ISSUE THREAD

**Issue by amtopel** [adobe/xmp-docs#11]
Hi, I was wondering if I could ask a question about using the XMP library.  It seems that the XMP forum has been removed or something from the Adobe website.

I'm using the XMP SDK to implement in a Windows property handler.  Basically I've created a COM class which is instantiated by Windows File Explorer whenever it encounters a PDF file.  My class uses the XMP library to get and set metadata within each file that Explorer encounters.

In any event, I'm initializing the XMP Meta and File libraries within my class's constructor, which seems to work okay.  However, when terminating those libraries within the destructor, I inevitably get an assertion errors and null pointer errors that crash the program.  I'm not sure, but perhaps it's because File Explorer has created several instances of my class, and so terminating the libraries by one class leads to problems (just a guess).

So I was wondering if you had any input on where to properly terminate the XMP libraries when used by a property handler.  Can they be terminated within DLLCanUnloadNow?  Thanks for any input!

**Comment by anjankaur** [comment]
@angupt Can help you in this.

**Comment by angupt** [comment]
@amtopel , XMPMeta and XMPFiles should be initialise/terminate once per application so you should call them from somewhere in your code which is called once.  If you are calling them from constructor/ destructor of your class then they should be called in a thread safe manner(protected by some mutexes). Also, if you are initialising XMPFiles, then there is no need to initialise XMPMeta as XMPFiles initialise XMPMeta too.

**Comment by amtopel** [comment]
Anuj,

Also, I’ve determined that calling OpenFile results in some delays in my property handler.  Do you have any tricks to make it speed up?  I’ve tried all sorts of options, including kXMPFiles_OpenOnlyXMP.  Do you have any tips?  Thank you again for all your help.

Adam

**Comment by angupt** [comment]
@amtopel if you need to open only pdf files then you can pass format as kXMP_PDFFile and try to pass flags kXMPFiles_ForceGivenHandler | kXMPFiles_OpenUseSmartHandler in OPenFile api. Hope this will reduce the OpenFile api timing.

**Comment by amtopel** [comment]
Going back to my original question, I discovered I can initialize the SXMPFiles library in a constructor using a local static variable, like this:

`static BOOL init = SXMPFiles::Initialize();`

This ensures that the initializing function takes place only once.  HOWEVER, I'm still not sure where to terminate the library.  I've tried terminating it in DLLCanUnloadNow(), like this:

```
STDAPI DllCanUnloadNow(void) {

	HRESULT hr = _AtlModule.DllCanUnloadNow();
	if (hr == S_OK)	{

		SXMPFiles::Terminate();

	}
	return hr;
}
```
But that crashes my program entirely.  Do you have any further advice on how to cleanly initialize and terminate the library in a COM class/DLL?

**Comment by amtopel** [comment]
I've also tried this, but it also crashes:

```
void __stdcall TerminationCallback(DWORD_PTR dw) {
    SXMPFiles::Terminate();
}
HRESULT CMyPropertyHandler::FinalConstruct() {
    static BOOL init = SXMPFiles::Initialize();
    static HRESULT destruct = _pAtlModule->AddTermFunc(TerminationCallback, NULL);
    return S_OK;
}
```

Can I get away with just not terminating the libraries?  I can't figure out a way to terminate them without causing a crash.

**Comment by angupt** [comment]
@amtopel can you provide the crash call stack? Also, how about delay in OpenFile api that you mentioned previously? Did you tried the flags I suggested?

**Comment by amtopel** [comment]
I tried the suggested flags, but I'm not sure they helped.  On the other hand, I've been testing my program with opening around 1000 files, so perhaps the delay is unavoidable.  It seems that opening around 1000 files takes a couple seconds.  I'm not sure if it should be faster.

I'll also try to obtain the crash log for you.

On other note: is it safe to call SXMPFiles::Initialize() and SXMPFiles::Terminate() from DllMain()?  The best practices for DllMain are here: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices.   I'm not sure if SXMPFiles::Initialize() and SXMPFiles::Terminate() fall within the safe uses.  Do you have any thoughts?
________________________________

**Comment by angupt** [comment]
@amtopel As per the documentation, 

> The ideal DllMain would be just an empty stub.

So, I think, you should not call `SXMPFiles::Initialize() and SXMPFiles::Terminate()` from DllMain api.

`SXMPFiles::Initialize() and SXMPFiles::Terminate()` should be called in Singleton fashion i.e. it should be called once per application.
You can refer C++ [call_once](https://en.cppreference.com/w/cpp/thread/call_once) and [once_flag](https://en.cppreference.com/w/cpp/thread/once_flag) and see if they can help.
